# Generated by Django 4.2.20 on 2025-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pages', models.IntegerField()),
                ('published', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
