# Generated by Django 5.2 on 2025-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='Articles_ar_created_0d4aed_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['views'], name='Articles_ar_views_901735_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['likes'], name='Articles_ar_likes_82644a_idx'),
        ),
    ]
