"""db init

Revision ID: 9bbf0a531ef1
Revises: 
Create Date: 2024-07-24 21:50:40.980008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bbf0a531ef1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("owner_id", sa.INTEGER(), nullable=True),
        # sa.ForeignKeyConstraint(
        #     ["owner_id"],
        #     ["user.id"],
        # ),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.Column("username", sa.VARCHAR(), nullable=True),
        sa.Column("password", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
    )
    # op.create_index("ix_user_username", "user", ["username"], unique=1)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    op.drop_table("item")
    # ### end Alembic commands ###
