# Generated by Django 5.0.1 on 2024-02-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='communities.post')),
                ('fixed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('communities.post',),
        ),
    ]
