# Generated by Django 5.0.1 on 2024-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_adminpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPost',
            fields=[
            ],
            options={
                'ordering': ['-likes'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communities.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
