# Generated by Django 5.0.1 on 2024-03-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_popularpost_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularpost',
            options={'ordering': ['-likes', '-created_at']},
        ),
    ]
