# Generated by Django 5.0.1 on 2024-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_no',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', False)), fields=('community', 'post_no'), name='unique_community_post_no'),
        ),
    ]
